import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { dbconfig } from "@/utils/dbconfig";
import { Toaster } from "@/components/ui/toaster";
import StoreProvider from "./global/storeprovider";
import Header from "./static/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbconfig()
  return (
    <StoreProvider>
          <html lang="en">
      <body className={`${inter.className}  bg-slate-100`}>
        <div className="w-full flex flex-col items-center justify-center">
        <Header/>
         <div className="w-[90%] mt-5 h-screen flex justify-center">  {children}</div>
        </div>
        </body>
    </html>
    </StoreProvider>

  );
}
